---
- name: EOS Show Commands
  hosts: all
  gather_facts: false
  connection: network_cli

  vars:
    ansible_network_os: eos
    ansible_user: "{{ username }}"
    ansible_password: "{{ password }}"
    ansible_become: true
    ansible_become_method: enable

  tasks:
    - name: eos show commands
      eos_command:
        commands:
          - show version
      register: output

    - name: show output
      debug:
        var: output